kind: pipeline
type: exec
name: default
   
steps:
- name: test
  settings:
    context: ./home/ramraja/
  commands:
    - cd $HOME
    - mkdir WTF

# kind: pipeline
# steps:
# - name: deploy
#   image: node:latest
#   commands:
#     - npm install
#     - npm run serve