version: '3'
services:
  portfolio:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
  server:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - '/app/node_modules'
    ports:
      - '3000:3000'    
