version: '3'
services:
  portfolio:
    container_name: portimusprime
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
